### PR TITLE
Summary table for Procedure Type vs Notice Subtype (TEDEFO-2705) added

### PR DESCRIPTION
**Pull request by YvesJo**

### CODE REVIEW

**Review by bertrand-lorentz — CHANGES_REQUESTED** [review]
It seems there's a problem with the table structure, the first column is not displayed correctly.

In any case, this table is not readable on any screen, it's too wide. We laready have tables like this, but let's not add more.
I'd suggest to try to present this information in another way. Or have this information provided as part of the "metadata reference".

**Comment by YvesJo** [comment]
From a usability perspective, having to scroll may not be the best.
Having the information in the metadata section will:

- require some programming to automatically extract information from the DB and build the pages,
- not provide the overall overview to non-techies unless additional operations are performed on their side,

So, I'm not convinced this would be a better option.

There are some other options left:

- change the table orientation,
- reduce the number of columns by grouping columns for which non of the codes are allowed.

Any thought or alternate option?

**Comment by pdonohoe** [comment]
Sorry I am late to seeing this. When I generate the HTML page locally, I don't see the first column of the table, listing the procedure types. I just see a lot of "X", "x", etc, with no explanation of what they mean.

I do have a suggestion for the problem of the size of the table: split it into three tables, for Planning, Competition and Result notice subtypes.

**Comment by pdonohoe** [comment]
The separation of the tables make them much easier to view and to read.

- The bold emphasis was not showing on my browser, so I changed _*X*_ to *_X_* to correct it
- Table 10 was misaligned: the cols= row had one too many column width definitions, and the rows for the subtypes one column too few. I added new cells at the end of each subtype row with |-- to align them. But I assume that the values are wrong, so they will need to be reviewed.
- Some of the values have lower-case "x". Is this correct? If so, what does it mean?

**Review by bertrand-lorentz — APPROVED** [review]
I still have reservation on the tabular format, and it seems we're trying to say too much at the same time: for each subtype, if the procedure type is allowed or forbidden, if a specific value is allowed, and if the procedure can be accelerated.

But I don't have the time to look into alternatives, so OK for me.

**Review by pdonohoe — APPROVED** [review]

**Pull request merged**
