### PR TITLE
Updated Documention Section on Contract Modification (TEDEFO-3049)

### PR DESCRIPTION
**Pull request by YvesJo**

### CODE REVIEW

**Review by pdonohoe — COMMENTED** [review]
The new text is very clear.
Has the field for "Modification Previous Notice Section Identifier" changed from BT-1501(s)-Contract to BT-1501(p)-Contract? Or is that a typo?
Also, with everything else explained clearly, I am now a bit confused for what this field should contain. As it relates to a Contract Modification, can it only contain the ID of the Lot associated to the Contract? Or could it contain, for example "PROCEDURE"? It would be good to add some information on this.

**Comment by YvesJo** [comment]
The change in field from BT-1501(s)-Contract to BT-1501(p)-Contract is intentional. The field may now contain anything it could already except the reference to the Contract. This will help prevent inappropriate backporting and detect there is a change;
I will propose an updated text.

**Comment by pdonohoe** [comment]
schemeName="notice-id-ref" is missing from efbc:ChangedNoticeIdentifier

**Comment by pdonohoe** [comment]
Much better @YvesJo . But the values in the XML example for BT-1501(p)-Contract reference LOTs, which is not in the list of items for Modified Notice Part Reference. Also, add a return before the list so that it displays as a bulleted list.

**Comment by YvesJo** [comment]
applied needed fixes

**Review by pdonohoe — APPROVED** [review]
Perfect!

**Pull request merged**
