### PR TITLE
DAP unpublish example (TEDEFO-1683)

### PR DESCRIPTION
**Pull request by YvesJo**

### CODE REVIEW

**Review by pdonohoe — APPROVED** [review]
Text and XML fine. I fixed a minor indentation issue.

**Comment by bertrand-lorentz** [comment]
I think this could also apply to the earlier versions of the docs.
If yes, I will do the necessary to get this first merged into 1.0.x, and then propagated to the other versions.

**Comment by bertrand-lorentz** [comment]
New PR to 1.0.x is PR #56 

If that other PR is OK, this will be closed.

**Comment by bertrand-lorentz** [comment]
This change was merged into 1.0.x via PR #56, and propagated to all other branches via other PRs.
So I'm closing this PR without merging.

**Pull request closed without merging**
